# Generated by Django 5.0.2 on 2024-07-05 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordentry',
            name='meeting_name',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='recordentry',
            name='meeting_subject',
            field=models.CharField(blank=True, default='Default Meeting Subject', max_length=70, null=True),
        ),
    ]
